name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0' # The Go version to download (if necessary) and use.

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run vet
        run: |
          go vet .

      - name: Run Lint
        run: |
          golint_files=$(golint .)
          if [[ -n ${golint_files} ]]; then
              echo 'fix the filing linting errors:'
              echo "${golint_files}"
              exit 1
          fi
          exit 0

      - name: Run fmt
        run: |
          gofmt_files=$(gofmt -l .)
          if [[ -n ${gofmt_files} ]]; then
              echo 'gofmt needs running on the following files:'
              echo "${gofmt_files}"
              exit 1
          fi
          exit 0


